[19/Jan/2021 00:04:32] django.request - ERROR - Internal Server Error: /user/admin/
Traceback (most recent call last):
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/mixins.py", line 56, in retrieve
    return Response(serializer.data)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/fields.py", line 1905, in to_representation
    return method(value)
  File "/home/NimG_Unit/var/UniProject/planb_backend/accounts/serializers/serializer_user.py", line 21, in check_phone_number_visiblity
    return User.objects.filter(username=instance.username).id
AttributeError: 'QuerySet' object has no attribute 'id'
[19/Jan/2021 00:05:27] django.request - ERROR - Internal Server Error: /user/admin/
Traceback (most recent call last):
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/djangorestframework_camel_case/render.py", line 9, in render
    return super().render(
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib64/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/NimG_Unit/var/UniProject/penv/lib64/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib64/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PhoneNumber is not JSON serializable
